name: cuapps_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  jaspr: ^0.21.1
  jaspr_router: ^0.7.3

dev_dependencies:
  build_runner: ^2.8.0
  jaspr_builder: ^0.21.1
  jaspr_lints: ^0.5.1
  jaspr_web_compilers: ^4.2.3
  lints: ^6.0.0

jaspr:
  mode: static
