name: cuapps_website
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  jaspr: ^0.22.2
  jaspr_router: ^0.8.1

dev_dependencies:
  build_runner: ^2.11.0
  build_web_compilers: ^4.4.9
  jaspr_builder: ^0.22.2
  jaspr_lints: ^0.6.0
  lints: ^6.1.0

jaspr:
  mode: static
